from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import async_session
from app.models import (
    Facility, Doctor, Nurse, Patient, InventoryStock,
    AIInsight, DiseaseSpike, HealthTrend, VillageCondition,
)

SEED_FACILITIES = [
    {"id": "phc-madhurawada", "name": "PHC Madhurawada", "facility_type": "PHC", "location": "Madhurawada", "overall_risk": "Critical", "today_opd": 312, "medicine_risk": "High", "disease_spike": "High", "bed_occupancy": 96},
    {"id": "chc-bheemunipatnam", "name": "CHC Bheemunipatnam", "facility_type": "CHC", "location": "Bheemunipatnam", "overall_risk": "High", "today_opd": 248, "medicine_risk": "High", "disease_spike": "Medium", "bed_occupancy": 82},
    {"id": "phc-gajuwaka", "name": "PHC Gajuwaka", "facility_type": "PHC", "location": "Gajuwaka", "overall_risk": "High", "today_opd": 276, "medicine_risk": "Medium", "disease_spike": "Medium", "bed_occupancy": 78},
    {"id": "phc-ananthapuram", "name": "PHC Ananthapuram", "facility_type": "PHC", "location": "Ananthapuram", "overall_risk": "Medium", "today_opd": 198, "medicine_risk": "Low", "disease_spike": "Low", "bed_occupancy": 56},
    {"id": "phc-pendurthi", "name": "PHC Pendurthi", "facility_type": "PHC", "location": "Pendurthi", "overall_risk": "Low", "today_opd": 162, "medicine_risk": "Low", "disease_spike": "Low", "bed_occupancy": 42},
    {"id": "chc-narsipatnam", "name": "CHC Narsipatnam", "facility_type": "CHC", "location": "Narsipatnam", "overall_risk": "Low", "today_opd": 134, "medicine_risk": "Low", "disease_spike": "Low", "bed_occupancy": 36},
    {"id": "phc-rushikonda", "name": "PHC Rushikonda", "facility_type": "PHC", "location": "Rushikonda", "overall_risk": "High", "today_opd": 205, "medicine_risk": "Medium", "disease_spike": "High", "bed_occupancy": 74},
    {"id": "phc-yendada", "name": "PHC Yendada", "facility_type": "PHC", "location": "Yendada", "overall_risk": "Medium", "today_opd": 178, "medicine_risk": "Low", "disease_spike": "Low", "bed_occupancy": 51},
    {"id": "chc-waltair", "name": "CHC Waltair", "facility_type": "CHC", "location": "Waltair Uplands", "overall_risk": "Critical", "today_opd": 342, "medicine_risk": "High", "disease_spike": "High", "bed_occupancy": 91},
    {"id": "phc-malkapuram", "name": "PHC Malkapuram", "facility_type": "PHC", "location": "Malkapuram", "overall_risk": "Medium", "today_opd": 156, "medicine_risk": "Medium", "disease_spike": "Low", "bed_occupancy": 48},
    {"id": "phc-gavaravaram", "name": "PHC Gavaravaram", "facility_type": "PHC", "location": "Gavaravaram", "overall_risk": "Low", "today_opd": 112, "medicine_risk": "Low", "disease_spike": "Low", "bed_occupancy": 31},
    {"id": "chc-devarapalle", "name": "CHC Devarapalle", "facility_type": "CHC", "location": "Devarapalle", "overall_risk": "High", "today_opd": 221, "medicine_risk": "High", "disease_spike": "Medium", "bed_occupancy": 79},
]

SEED_DOCTORS = [
    {"id": "doc-1", "name": "Dr. Kavya Menon", "facility_id": "phc-madhurawada", "specialty": "General Medicine", "attendance": "present", "patients_seen_today": 58, "max_capacity": 42, "active_patients": 138, "high_risk_patients": 23, "pending_reviews": 18, "workload_status": "critical"},
    {"id": "doc-2", "name": "Dr. Rajesh Kumar", "facility_id": "phc-madhurawada", "specialty": "Family Medicine", "attendance": "absent", "patients_seen_today": 0, "max_capacity": 40, "active_patients": 92, "high_risk_patients": 15, "pending_reviews": 14, "workload_status": "high"},
    {"id": "doc-3", "name": "Dr. Prakash Rao", "facility_id": "chc-bheemunipatnam", "specialty": "Emergency Medicine", "attendance": "present", "patients_seen_today": 46, "max_capacity": 48, "active_patients": 121, "high_risk_patients": 19, "pending_reviews": 11, "workload_status": "high"},
    {"id": "doc-4", "name": "Dr. Meera Shah", "facility_id": "phc-gajuwaka", "specialty": "Pediatrics", "attendance": "present", "patients_seen_today": 52, "max_capacity": 44, "active_patients": 113, "high_risk_patients": 17, "pending_reviews": 14, "workload_status": "high"},
    {"id": "doc-5", "name": "Dr. Nikhil Reddy", "facility_id": "phc-pendurthi", "specialty": "General Medicine", "attendance": "present", "patients_seen_today": 28, "max_capacity": 40, "active_patients": 74, "high_risk_patients": 7, "pending_reviews": 6, "workload_status": "normal"},
    {"id": "doc-6", "name": "Dr. Ananya Iyer", "facility_id": "chc-narsipatnam", "specialty": "Public Health", "attendance": "present", "patients_seen_today": 31, "max_capacity": 45, "active_patients": 65, "high_risk_patients": 5, "pending_reviews": 4, "workload_status": "normal"},
    {"id": "doc-7", "name": "Dr. Suresh Babu", "facility_id": "phc-ananthapuram", "specialty": "General Medicine", "attendance": "present", "patients_seen_today": 22, "max_capacity": 35, "active_patients": 45, "high_risk_patients": 4, "pending_reviews": 3, "workload_status": "normal"},
    {"id": "doc-8", "name": "Dr. Priya Nair", "facility_id": "phc-ananthapuram", "specialty": "Obstetrics", "attendance": "present", "patients_seen_today": 18, "max_capacity": 30, "active_patients": 38, "high_risk_patients": 6, "pending_reviews": 5, "workload_status": "normal"},
    {"id": "doc-9", "name": "Dr. Vikram Patel", "facility_id": "phc-rushikonda", "specialty": "Internal Medicine", "attendance": "present", "patients_seen_today": 44, "max_capacity": 40, "active_patients": 105, "high_risk_patients": 18, "pending_reviews": 12, "workload_status": "critical"},
    {"id": "doc-10", "name": "Dr. Sneha Reddy", "facility_id": "phc-rushikonda", "specialty": "Dermatology", "attendance": "absent", "patients_seen_today": 0, "max_capacity": 35, "active_patients": 58, "high_risk_patients": 3, "pending_reviews": 8, "workload_status": "high"},
    {"id": "doc-11", "name": "Dr. Arjun Varma", "facility_id": "phc-yendada", "specialty": "General Medicine", "attendance": "present", "patients_seen_today": 32, "max_capacity": 38, "active_patients": 82, "high_risk_patients": 9, "pending_reviews": 7, "workload_status": "normal"},
    {"id": "doc-12", "name": "Dr. Lakshmi Satyanarayana", "facility_id": "chc-waltair", "specialty": "Cardiology", "attendance": "present", "patients_seen_today": 61, "max_capacity": 50, "active_patients": 156, "high_risk_patients": 31, "pending_reviews": 22, "workload_status": "critical"},
    {"id": "doc-13", "name": "Dr. Ravi Teja", "facility_id": "chc-waltair", "specialty": "Orthopedics", "attendance": "present", "patients_seen_today": 38, "max_capacity": 42, "active_patients": 98, "high_risk_patients": 12, "pending_reviews": 9, "workload_status": "high"},
    {"id": "doc-14", "name": "Dr. Padmavathi", "facility_id": "phc-malkapuram", "specialty": "General Medicine", "attendance": "present", "patients_seen_today": 26, "max_capacity": 36, "active_patients": 68, "high_risk_patients": 8, "pending_reviews": 5, "workload_status": "normal"},
    {"id": "doc-15", "name": "Dr. Venkatesh Rao", "facility_id": "phc-gavaravaram", "specialty": "Pediatrics", "attendance": "present", "patients_seen_today": 15, "max_capacity": 30, "active_patients": 34, "high_risk_patients": 2, "pending_reviews": 2, "workload_status": "normal"},
    {"id": "doc-16", "name": "Dr. Sita Devi", "facility_id": "chc-devarapalle", "specialty": "Obstetrics", "attendance": "present", "patients_seen_today": 41, "max_capacity": 44, "active_patients": 112, "high_risk_patients": 20, "pending_reviews": 15, "workload_status": "high"},
    {"id": "doc-17", "name": "Dr. Mohan Krishna", "facility_id": "chc-devarapalle", "specialty": "General Medicine", "attendance": "absent", "patients_seen_today": 0, "max_capacity": 40, "active_patients": 88, "high_risk_patients": 14, "pending_reviews": 11, "workload_status": "high"},
]

SEED_NURSES = [
    {"id": "nurse-1", "name": "Sr. Lakshmi Devi", "facility_id": "phc-madhurawada", "assigned_villages": ["Madhurawada", "Rushikonda"], "assigned_patients": 82, "pending_follow_ups": 29, "completed_today": 17, "high_risk_follow_ups": 11, "workload_status": "critical"},
    {"id": "nurse-2", "name": "Sr. Mary D.", "facility_id": "phc-madhurawada", "assigned_villages": ["Madhurawada", "Yendada"], "assigned_patients": 76, "pending_follow_ups": 24, "completed_today": 12, "high_risk_follow_ups": 8, "workload_status": "high"},
    {"id": "nurse-3", "name": "Sr. Revathi", "facility_id": "chc-bheemunipatnam", "assigned_villages": ["Bheemunipatnam", "Tagarapuvalasa"], "assigned_patients": 73, "pending_follow_ups": 18, "completed_today": 21, "high_risk_follow_ups": 8, "workload_status": "high"},
    {"id": "nurse-4", "name": "Sr. Asha", "facility_id": "phc-gajuwaka", "assigned_villages": ["Gajuwaka", "Malkapuram"], "assigned_patients": 69, "pending_follow_ups": 23, "completed_today": 14, "high_risk_follow_ups": 10, "workload_status": "high"},
    {"id": "nurse-5", "name": "Sr. Jyothi", "facility_id": "phc-pendurthi", "assigned_villages": ["Pendurthi"], "assigned_patients": 48, "pending_follow_ups": 7, "completed_today": 16, "high_risk_follow_ups": 3, "workload_status": "normal"},
    {"id": "nurse-6", "name": "Sr. Padma", "facility_id": "phc-ananthapuram", "assigned_villages": ["Ananthapuram", "Gavaravaram"], "assigned_patients": 61, "pending_follow_ups": 15, "completed_today": 19, "high_risk_follow_ups": 7, "workload_status": "high"},
    {"id": "nurse-7", "name": "Sr. Sunitha", "facility_id": "chc-narsipatnam", "assigned_villages": ["Narsipatnam", "Devarapalle"], "assigned_patients": 54, "pending_follow_ups": 11, "completed_today": 20, "high_risk_follow_ups": 4, "workload_status": "normal"},
    {"id": "nurse-8", "name": "Sr. Kavitha", "facility_id": "phc-rushikonda", "assigned_villages": ["Rushikonda", "Beach Road"], "assigned_patients": 71, "pending_follow_ups": 22, "completed_today": 15, "high_risk_follow_ups": 9, "workload_status": "high"},
    {"id": "nurse-9", "name": "Sr. Rani", "facility_id": "phc-yendada", "assigned_villages": ["Yendada", "Seethammadhara"], "assigned_patients": 56, "pending_follow_ups": 12, "completed_today": 18, "high_risk_follow_ups": 5, "workload_status": "normal"},
    {"id": "nurse-10", "name": "Sr. Vijaya", "facility_id": "chc-waltair", "assigned_villages": ["Waltair Uplands", "Lawsons Bay"], "assigned_patients": 89, "pending_follow_ups": 31, "completed_today": 14, "high_risk_follow_ups": 15, "workload_status": "critical"},
    {"id": "nurse-11", "name": "Sr. Devika", "facility_id": "phc-malkapuram", "assigned_villages": ["Malkapuram", "Steel Plant"], "assigned_patients": 44, "pending_follow_ups": 9, "completed_today": 16, "high_risk_follow_ups": 4, "workload_status": "normal"},
    {"id": "nurse-12", "name": "Sr. Sujatha", "facility_id": "chc-devarapalle", "assigned_villages": ["Devarapalle", "Paderu"], "assigned_patients": 63, "pending_follow_ups": 19, "completed_today": 13, "high_risk_follow_ups": 8, "workload_status": "high"},
    {"id": "nurse-13", "name": "Sr. Annapurna", "facility_id": "phc-gavaravaram", "assigned_villages": ["Gavaravaram", "Chintapalle"], "assigned_patients": 38, "pending_follow_ups": 6, "completed_today": 14, "high_risk_follow_ups": 2, "workload_status": "normal"},
]

SEED_PATIENTS = [
    {"id": "pat-001", "name": "Sabrina Rao", "age": 39, "gender": "Female", "phone": "+91 98765 12001", "village": "Madhurawada", "facility_id": "phc-madhurawada", "assigned_doctor_id": "doc-1", "assigned_nurse_id": "nurse-1", "risk_score": "High", "condition": "Fever with dehydration", "conditions": ["Fever", "Dehydration"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-05", "avatar": "SR"},
    {"id": "pat-002", "name": "Anil Varma", "age": 62, "gender": "Male", "phone": "+91 98765 12002", "village": "Madhurawada", "facility_id": "phc-madhurawada", "assigned_doctor_id": "doc-1", "assigned_nurse_id": "nurse-1", "risk_score": "High", "condition": "Diabetes and hypertension", "conditions": ["Diabetes", "Hypertension"], "follow_up_status": "overdue", "last_visit": "2026-07-01", "next_follow_up": "2026-07-03", "avatar": "AV"},
    {"id": "pat-003", "name": "Lakshmi Devi", "age": 28, "gender": "Female", "phone": "+91 98765 12003", "village": "Bheemunipatnam", "facility_id": "chc-bheemunipatnam", "assigned_doctor_id": "doc-3", "assigned_nurse_id": "nurse-3", "risk_score": "Medium", "condition": "Pregnancy risk and anemia", "conditions": ["Pregnancy risk", "Anemia"], "follow_up_status": "pending", "last_visit": "2026-07-03", "next_follow_up": "2026-07-06", "avatar": "LD"},
    {"id": "pat-004", "name": "Rafiq Khan", "age": 45, "gender": "Male", "phone": "+91 98765 12004", "village": "Gajuwaka", "facility_id": "phc-gajuwaka", "assigned_doctor_id": "doc-4", "assigned_nurse_id": "nurse-4", "risk_score": "High", "condition": "ARI and asthma", "conditions": ["ARI", "Asthma"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-05", "avatar": "RK"},
    {"id": "pat-005", "name": "Mariyamma Devi", "age": 62, "gender": "Female", "phone": "+91 98765 12005", "village": "Pendurthi", "facility_id": "phc-pendurthi", "assigned_doctor_id": "doc-5", "assigned_nurse_id": "nurse-5", "risk_score": "High", "condition": "Diabetes Type 2", "conditions": ["Diabetes Type 2"], "follow_up_status": "completed", "last_visit": "2026-07-02", "next_follow_up": "2026-07-12", "avatar": "MD"},
    {"id": "pat-006", "name": "Venkata Ramana", "age": 45, "gender": "Male", "phone": "+91 98765 12006", "village": "Bheemunipatnam", "facility_id": "chc-bheemunipatnam", "assigned_doctor_id": "doc-3", "assigned_nurse_id": "nurse-3", "risk_score": "Medium", "condition": "Hypertension", "conditions": ["Hypertension"], "follow_up_status": "completed", "last_visit": "2026-06-30", "next_follow_up": "2026-07-14", "avatar": "VR"},
    {"id": "pat-007", "name": "Saraswati Bai", "age": 28, "gender": "Female", "phone": "+91 98765 12007", "village": "Gajuwaka", "facility_id": "phc-gajuwaka", "assigned_doctor_id": "doc-4", "assigned_nurse_id": "nurse-4", "risk_score": "Low", "condition": "Antenatal care", "conditions": ["Antenatal"], "follow_up_status": "completed", "last_visit": "2026-06-29", "next_follow_up": "2026-07-20", "avatar": "SB"},
    {"id": "pat-008", "name": "Rajeshwari", "age": 55, "gender": "Female", "phone": "+91 98765 12008", "village": "Pendurthi", "facility_id": "phc-pendurthi", "assigned_doctor_id": "doc-5", "assigned_nurse_id": "nurse-5", "risk_score": "Medium", "condition": "Hypertension", "conditions": ["Hypertension"], "follow_up_status": "pending", "last_visit": "2026-07-03", "next_follow_up": "2026-07-07", "avatar": "RW"},
    {"id": "pat-009", "name": "Srinivasa Rao", "age": 48, "gender": "Male", "phone": "+91 98765 12009", "village": "Ananthapuram", "facility_id": "phc-ananthapuram", "assigned_doctor_id": "doc-7", "assigned_nurse_id": "nurse-6", "risk_score": "Medium", "condition": "Diabetes Type 2", "conditions": ["Diabetes Type 2"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-08", "avatar": "SR"},
    {"id": "pat-010", "name": "Lakshmi Narasamma", "age": 34, "gender": "Female", "phone": "+91 98765 12010", "village": "Ananthapuram", "facility_id": "phc-ananthapuram", "assigned_doctor_id": "doc-8", "assigned_nurse_id": "nurse-6", "risk_score": "Low", "condition": "Antenatal care", "conditions": ["Antenatal"], "follow_up_status": "completed", "last_visit": "2026-07-01", "next_follow_up": "2026-07-15", "avatar": "LN"},
    {"id": "pat-011", "name": "Gangadhara Rao", "age": 67, "gender": "Male", "phone": "+91 98765 12011", "village": "Ananthapuram", "facility_id": "phc-ananthapuram", "assigned_doctor_id": "doc-7", "assigned_nurse_id": "nurse-6", "risk_score": "High", "condition": "COPD and hypertension", "conditions": ["COPD", "Hypertension"], "follow_up_status": "overdue", "last_visit": "2026-06-28", "next_follow_up": "2026-07-02", "avatar": "GR"},
    {"id": "pat-012", "name": "Durga Prasad", "age": 52, "gender": "Male", "phone": "+91 98765 12012", "village": "Narsipatnam", "facility_id": "chc-narsipatnam", "assigned_doctor_id": "doc-6", "assigned_nurse_id": "nurse-7", "risk_score": "Medium", "condition": "Hypertension and diabetes", "conditions": ["Hypertension", "Diabetes"], "follow_up_status": "pending", "last_visit": "2026-07-03", "next_follow_up": "2026-07-06", "avatar": "DP"},
    {"id": "pat-013", "name": "Parvathi Devi", "age": 35, "gender": "Female", "phone": "+91 98765 12013", "village": "Narsipatnam", "facility_id": "chc-narsipatnam", "assigned_doctor_id": "doc-6", "assigned_nurse_id": "nurse-7", "risk_score": "Low", "condition": "Antenatal care", "conditions": ["Antenatal"], "follow_up_status": "completed", "last_visit": "2026-07-01", "next_follow_up": "2026-07-15", "avatar": "PD"},
    {"id": "pat-014", "name": "Krishna Murthy", "age": 71, "gender": "Male", "phone": "+91 98765 12014", "village": "Devarapalle", "facility_id": "chc-narsipatnam", "assigned_doctor_id": "doc-6", "assigned_nurse_id": "nurse-7", "risk_score": "High", "condition": "COPD with respiratory infection", "conditions": ["COPD", "Respiratory infection"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-05", "avatar": "KM"},
    {"id": "pat-015", "name": "Annapurna", "age": 42, "gender": "Female", "phone": "+91 98765 12015", "village": "Rushikonda", "facility_id": "phc-rushikonda", "assigned_doctor_id": "doc-9", "assigned_nurse_id": "nurse-8", "risk_score": "High", "condition": "Dengue fever", "conditions": ["Dengue", "Fever"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-05", "avatar": "AN"},
    {"id": "pat-016", "name": "Ramesh Babu", "age": 58, "gender": "Male", "phone": "+91 98765 12016", "village": "Rushikonda", "facility_id": "phc-rushikonda", "assigned_doctor_id": "doc-9", "assigned_nurse_id": "nurse-8", "risk_score": "Critical", "condition": "Cardiac arrest recovery", "conditions": ["Cardiac", "Hypertension"], "follow_up_status": "pending", "last_visit": "2026-07-05", "next_follow_up": "2026-07-05", "avatar": "RB"},
    {"id": "pat-017", "name": "Sunitha Kumari", "age": 29, "gender": "Female", "phone": "+91 98765 12017", "village": "Beach Road", "facility_id": "phc-rushikonda", "assigned_doctor_id": "doc-10", "assigned_nurse_id": "nurse-8", "risk_score": "Low", "condition": "Skin infection", "conditions": ["Dermatitis"], "follow_up_status": "completed", "last_visit": "2026-07-02", "next_follow_up": "2026-07-16", "avatar": "SK"},
    {"id": "pat-018", "name": "Murali Krishna", "age": 47, "gender": "Male", "phone": "+91 98765 12018", "village": "Yendada", "facility_id": "phc-yendada", "assigned_doctor_id": "doc-11", "assigned_nurse_id": "nurse-9", "risk_score": "Medium", "condition": "Type 2 Diabetes", "conditions": ["Diabetes"], "follow_up_status": "pending", "last_visit": "2026-07-03", "next_follow_up": "2026-07-10", "avatar": "MK"},
    {"id": "pat-019", "name": "Geetha Rani", "age": 36, "gender": "Female", "phone": "+91 98765 12019", "village": "Seethammadhara", "facility_id": "phc-yendada", "assigned_doctor_id": "doc-11", "assigned_nurse_id": "nurse-9", "risk_score": "Low", "condition": "Post-natal care", "conditions": ["Post-natal"], "follow_up_status": "completed", "last_visit": "2026-06-28", "next_follow_up": "2026-07-12", "avatar": "GR"},
    {"id": "pat-020", "name": "Bala Subrahmanyam", "age": 73, "gender": "Male", "phone": "+91 98765 12020", "village": "Waltair Uplands", "facility_id": "chc-waltair", "assigned_doctor_id": "doc-12", "assigned_nurse_id": "nurse-10", "risk_score": "Critical", "condition": "Heart failure with arrhythmia", "conditions": ["Heart failure", "Arrhythmia"], "follow_up_status": "pending", "last_visit": "2026-07-05", "next_follow_up": "2026-07-05", "avatar": "BS"},
    {"id": "pat-021", "name": "Usha Rani", "age": 54, "gender": "Female", "phone": "+91 98765 12021", "village": "Waltair Uplands", "facility_id": "chc-waltair", "assigned_doctor_id": "doc-12", "assigned_nurse_id": "nurse-10", "risk_score": "High", "condition": "Uncontrolled hypertension", "conditions": ["Hypertension", "Diabetes"], "follow_up_status": "overdue", "last_visit": "2026-06-25", "next_follow_up": "2026-06-28", "avatar": "UR"},
    {"id": "pat-022", "name": "Suresh Kumar", "age": 41, "gender": "Male", "phone": "+91 98765 12022", "village": "Lawsons Bay", "facility_id": "chc-waltair", "assigned_doctor_id": "doc-13", "assigned_nurse_id": "nurse-10", "risk_score": "Medium", "condition": "Fracture - left wrist", "conditions": ["Fracture"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-11", "avatar": "SK"},
    {"id": "pat-023", "name": "Kamala Devi", "age": 65, "gender": "Female", "phone": "+91 98765 12023", "village": "Malkapuram", "facility_id": "phc-malkapuram", "assigned_doctor_id": "doc-14", "assigned_nurse_id": "nurse-11", "risk_score": "Medium", "condition": "Osteoarthritis", "conditions": ["Osteoarthritis"], "follow_up_status": "pending", "last_visit": "2026-07-03", "next_follow_up": "2026-07-08", "avatar": "KD"},
    {"id": "pat-024", "name": "Gopal Krishna", "age": 38, "gender": "Male", "phone": "+91 98765 12024", "village": "Steel Plant", "facility_id": "phc-malkapuram", "assigned_doctor_id": "doc-14", "assigned_nurse_id": "nurse-11", "risk_score": "Low", "condition": "Migraine", "conditions": ["Migraine"], "follow_up_status": "completed", "last_visit": "2026-06-30", "next_follow_up": "2026-07-14", "avatar": "GK"},
    {"id": "pat-025", "name": "Padmaja", "age": 31, "gender": "Female", "phone": "+91 98765 12025", "village": "Gavaravaram", "facility_id": "phc-gavaravaram", "assigned_doctor_id": "doc-15", "assigned_nurse_id": "nurse-13", "risk_score": "Low", "condition": "Antenatal - 7 months", "conditions": ["Antenatal"], "follow_up_status": "completed", "last_visit": "2026-07-01", "next_follow_up": "2026-07-08", "avatar": "PJ"},
    {"id": "pat-026", "name": "Rajesh", "age": 8, "gender": "Male", "phone": "+91 98765 12026", "village": "Chintapalle", "facility_id": "phc-gavaravaram", "assigned_doctor_id": "doc-15", "assigned_nurse_id": "nurse-13", "risk_score": "Medium", "condition": "Pediatric pneumonia", "conditions": ["Pneumonia", "Fever"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-06", "avatar": "RJ"},
    {"id": "pat-027", "name": "Savitri", "age": 44, "gender": "Female", "phone": "+91 98765 12027", "village": "Devarapalle", "facility_id": "chc-devarapalle", "assigned_doctor_id": "doc-16", "assigned_nurse_id": "nurse-12", "risk_score": "High", "condition": "High-risk pregnancy", "conditions": ["Pregnancy", "Anemia", "Hypertension"], "follow_up_status": "pending", "last_visit": "2026-07-05", "next_follow_up": "2026-07-05", "avatar": "SV"},
    {"id": "pat-028", "name": "Pullarao", "age": 59, "gender": "Male", "phone": "+91 98765 12028", "village": "Paderu", "facility_id": "chc-devarapalle", "assigned_doctor_id": "doc-17", "assigned_nurse_id": "nurse-12", "risk_score": "High", "condition": "Chronic bronchitis", "conditions": ["Bronchitis", "COPD"], "follow_up_status": "overdue", "last_visit": "2026-06-27", "next_follow_up": "2026-06-30", "avatar": "PR"},
    {"id": "pat-029", "name": "Yamuna", "age": 26, "gender": "Female", "phone": "+91 98765 12029", "village": "Tagarapuvalasa", "facility_id": "chc-bheemunipatnam", "assigned_doctor_id": "doc-3", "assigned_nurse_id": "nurse-3", "risk_score": "Low", "condition": "Antenatal care - 5 months", "conditions": ["Antenatal"], "follow_up_status": "completed", "last_visit": "2026-07-02", "next_follow_up": "2026-07-16", "avatar": "YM"},
    {"id": "pat-030", "name": "Prasad", "age": 51, "gender": "Male", "phone": "+91 98765 12030", "village": "Madhurawada", "facility_id": "phc-madhurawada", "assigned_doctor_id": "doc-1", "assigned_nurse_id": "nurse-1", "risk_score": "Critical", "condition": "Diabetic ketoacidosis", "conditions": ["Diabetes", "DKA"], "follow_up_status": "pending", "last_visit": "2026-07-05", "next_follow_up": "2026-07-05", "avatar": "PS"},
    {"id": "pat-031", "name": "Sudha Rani", "age": 33, "gender": "Female", "phone": "+91 98765 12031", "village": "Gajuwaka", "facility_id": "phc-gajuwaka", "assigned_doctor_id": "doc-4", "assigned_nurse_id": "nurse-4", "risk_score": "Medium", "condition": "Thyroid disorder", "conditions": ["Hypothyroidism"], "follow_up_status": "pending", "last_visit": "2026-07-03", "next_follow_up": "2026-07-10", "avatar": "SR"},
    {"id": "pat-032", "name": "Chandra Mohan", "age": 60, "gender": "Male", "phone": "+91 98765 12032", "village": "Narsipatnam", "facility_id": "chc-narsipatnam", "assigned_doctor_id": "doc-6", "assigned_nurse_id": "nurse-7", "risk_score": "High", "condition": "Chronic kidney disease", "conditions": ["CKD", "Hypertension"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-06", "avatar": "CM"},
    {"id": "pat-033", "name": "Jyothi", "age": 22, "gender": "Female", "phone": "+91 98765 12033", "village": "Pendurthi", "facility_id": "phc-pendurthi", "assigned_doctor_id": "doc-5", "assigned_nurse_id": "nurse-5", "risk_score": "Low", "condition": "Anemia - iron deficiency", "conditions": ["Anemia"], "follow_up_status": "completed", "last_visit": "2026-06-29", "next_follow_up": "2026-07-13", "avatar": "JT"},
    {"id": "pat-034", "name": "Veerabhadra Rao", "age": 68, "gender": "Male", "phone": "+91 98765 12034", "village": "Ananthapuram", "facility_id": "phc-ananthapuram", "assigned_doctor_id": "doc-7", "assigned_nurse_id": "nurse-6", "risk_score": "High", "condition": "Post-stroke rehabilitation", "conditions": ["Stroke", "Hypertension"], "follow_up_status": "overdue", "last_visit": "2026-06-26", "next_follow_up": "2026-06-29", "avatar": "VR"},
    {"id": "pat-035", "name": "Latha", "age": 40, "gender": "Female", "phone": "+91 98765 12035", "village": "Rushikonda", "facility_id": "phc-rushikonda", "assigned_doctor_id": "doc-9", "assigned_nurse_id": "nurse-8", "risk_score": "Medium", "condition": "Malaria - P. vivax", "conditions": ["Malaria", "Fever"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-06", "avatar": "LT"},
    {"id": "pat-036", "name": "Hanumanthu", "age": 75, "gender": "Male", "phone": "+91 98765 12036", "village": "Waltair Uplands", "facility_id": "chc-waltair", "assigned_doctor_id": "doc-12", "assigned_nurse_id": "nurse-10", "risk_score": "Critical", "condition": "Acute MI - stent placed", "conditions": ["MI", "Heart failure"], "follow_up_status": "pending", "last_visit": "2026-07-05", "next_follow_up": "2026-07-06", "avatar": "HN"},
    {"id": "pat-037", "name": "Saroja", "age": 48, "gender": "Female", "phone": "+91 98765 12037", "village": "Malkapuram", "facility_id": "phc-malkapuram", "assigned_doctor_id": "doc-14", "assigned_nurse_id": "nurse-11", "risk_score": "Medium", "condition": "Asthma - moderate persistent", "conditions": ["Asthma"], "follow_up_status": "pending", "last_visit": "2026-07-03", "next_follow_up": "2026-07-07", "avatar": "SJ"},
    {"id": "pat-038", "name": "Nagaraju", "age": 30, "gender": "Male", "phone": "+91 98765 12038", "village": "Devarapalle", "facility_id": "chc-devarapalle", "assigned_doctor_id": "doc-16", "assigned_nurse_id": "nurse-12", "risk_score": "Low", "condition": "Appendectomy recovery", "conditions": ["Post-surgery"], "follow_up_status": "completed", "last_visit": "2026-07-02", "next_follow_up": "2026-07-09", "avatar": "NJ"},
    {"id": "pat-039", "name": "Shanthi", "age": 56, "gender": "Female", "phone": "+91 98765 12039", "village": "Yendada", "facility_id": "phc-yendada", "assigned_doctor_id": "doc-11", "assigned_nurse_id": "nurse-9", "risk_score": "High", "condition": "Rheumatoid arthritis flare", "conditions": ["RA", "Anemia"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-06", "avatar": "SH"},
    {"id": "pat-040", "name": "Balu", "age": 12, "gender": "Male", "phone": "+91 98765 12040", "village": "Gavaravaram", "facility_id": "phc-gavaravaram", "assigned_doctor_id": "doc-15", "assigned_nurse_id": "nurse-13", "risk_score": "Medium", "condition": "Typhoid fever", "conditions": ["Typhoid", "Fever"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-06", "avatar": "BL"},
    {"id": "pat-041", "name": "Meena Kumari", "age": 45, "gender": "Female", "phone": "+91 98765 12041", "village": "Bheemunipatnam", "facility_id": "chc-bheemunipatnam", "assigned_doctor_id": "doc-3", "assigned_nurse_id": "nurse-3", "risk_score": "High", "condition": "Gallstones - awaiting surgery", "conditions": ["Cholelithiasis"], "follow_up_status": "pending", "last_visit": "2026-07-03", "next_follow_up": "2026-07-05", "avatar": "MK"},
    {"id": "pat-042", "name": "Tirupathi Rao", "age": 63, "gender": "Male", "phone": "+91 98765 12042", "village": "Madhurawada", "facility_id": "phc-madhurawada", "assigned_doctor_id": "doc-1", "assigned_nurse_id": "nurse-1", "risk_score": "High", "condition": "COPD exacerbation", "conditions": ["COPD", "Diabetes"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-05", "avatar": "TR"},
    {"id": "pat-043", "name": "Kavitha", "age": 27, "gender": "Female", "phone": "+91 98765 12043", "village": "Paderu", "facility_id": "chc-devarapalle", "assigned_doctor_id": "doc-16", "assigned_nurse_id": "nurse-12", "risk_score": "Medium", "condition": "Ectopic pregnancy - monitoring", "conditions": ["Ectopic pregnancy"], "follow_up_status": "pending", "last_visit": "2026-07-05", "next_follow_up": "2026-07-06", "avatar": "KV"},
    {"id": "pat-044", "name": "Ravi Kumar", "age": 35, "gender": "Male", "phone": "+91 98765 12044", "village": "Steel Plant", "facility_id": "phc-malkapuram", "assigned_doctor_id": "doc-14", "assigned_nurse_id": "nurse-11", "risk_score": "Low", "condition": "Lower back pain", "conditions": ["Lumbago"], "follow_up_status": "completed", "last_visit": "2026-07-01", "next_follow_up": "2026-07-15", "avatar": "RK"},
    {"id": "pat-045", "name": "Asha Rani", "age": 50, "gender": "Female", "phone": "+91 98765 12045", "village": "Lawsons Bay", "facility_id": "chc-waltair", "assigned_doctor_id": "doc-12", "assigned_nurse_id": "nurse-10", "risk_score": "High", "condition": "Atrial fibrillation", "conditions": ["AFib", "Hypertension"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-05", "avatar": "AR"},
    {"id": "pat-046", "name": "Siva Prasad", "age": 44, "gender": "Male", "phone": "+91 98765 12046", "village": "Gajuwaka", "facility_id": "phc-gajuwaka", "assigned_doctor_id": "doc-4", "assigned_nurse_id": "nurse-4", "risk_score": "Medium", "condition": "Peptic ulcer", "conditions": ["Gastric ulcer"], "follow_up_status": "pending", "last_visit": "2026-07-03", "next_follow_up": "2026-07-08", "avatar": "SP"},
    {"id": "pat-047", "name": "Lakshmi", "age": 19, "gender": "Female", "phone": "+91 98765 12047", "village": "Chintapalle", "facility_id": "phc-gavaravaram", "assigned_doctor_id": "doc-15", "assigned_nurse_id": "nurse-13", "risk_score": "Low", "condition": "Iron deficiency anemia", "conditions": ["Anemia"], "follow_up_status": "completed", "last_visit": "2026-06-28", "next_follow_up": "2026-07-12", "avatar": "LM"},
    {"id": "pat-048", "name": "Rajam", "age": 61, "gender": "Female", "phone": "+91 98765 12048", "village": "Narsipatnam", "facility_id": "chc-narsipatnam", "assigned_doctor_id": "doc-6", "assigned_nurse_id": "nurse-7", "risk_score": "High", "condition": "Diabetic retinopathy", "conditions": ["Diabetes", "Retinopathy"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-06", "avatar": "RJ"},
    {"id": "pat-049", "name": "Krishnaiah", "age": 70, "gender": "Male", "phone": "+91 98765 12049", "village": "Seethammadhara", "facility_id": "phc-yendada", "assigned_doctor_id": "doc-11", "assigned_nurse_id": "nurse-9", "risk_score": "High", "condition": "Benign prostatic hyperplasia", "conditions": ["BPH"], "follow_up_status": "pending", "last_visit": "2026-07-03", "next_follow_up": "2026-07-06", "avatar": "KR"},
    {"id": "pat-050", "name": "Sarojini", "age": 38, "gender": "Female", "phone": "+91 98765 12050", "village": "Tagarapuvalasa", "facility_id": "chc-bheemunipatnam", "assigned_doctor_id": "doc-3", "assigned_nurse_id": "nurse-3", "risk_score": "Low", "condition": "UTI - treated", "conditions": ["UTI"], "follow_up_status": "completed", "last_visit": "2026-07-01", "next_follow_up": "2026-07-15", "avatar": "SJ"},
    {"id": "pat-051", "name": "Venkatesh", "age": 53, "gender": "Male", "phone": "+91 98765 12051", "village": "Rushikonda", "facility_id": "phc-rushikonda", "assigned_doctor_id": "doc-9", "assigned_nurse_id": "nurse-8", "risk_score": "High", "condition": "Hepatitis B - chronic", "conditions": ["Hepatitis B"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-06", "avatar": "VK"},
    {"id": "pat-052", "name": "Devi", "age": 46, "gender": "Female", "phone": "+91 98765 12052", "village": "Waltair Uplands", "facility_id": "chc-waltair", "assigned_doctor_id": "doc-13", "assigned_nurse_id": "nurse-10", "risk_score": "Medium", "condition": "Knee replacement - post-op", "conditions": ["Post-surgery", "Osteoarthritis"], "follow_up_status": "pending", "last_visit": "2026-07-04", "next_follow_up": "2026-07-11", "avatar": "DV"},
]

SEED_INVENTORY = [
    {"id": "stock-1", "name": "Paracetamol 650mg", "facility_id": "phc-madhurawada", "current_stock": 68, "avg_daily_usage": 31, "days_left": 2.2, "reorder_level": 180, "risk": "critical", "batch_number": "BATCH-001"},
    {"id": "stock-2", "name": "ORS packets", "facility_id": "phc-madhurawada", "current_stock": 92, "avg_daily_usage": 30, "days_left": 3.0, "reorder_level": 220, "risk": "high", "batch_number": "BATCH-002"},
    {"id": "stock-3", "name": "Amoxicillin", "facility_id": "chc-bheemunipatnam", "current_stock": 140, "avg_daily_usage": 42, "days_left": 3.3, "reorder_level": 260, "risk": "high", "batch_number": "BATCH-003"},
    {"id": "stock-4", "name": "Iron tablets", "facility_id": "chc-bheemunipatnam", "current_stock": 310, "avg_daily_usage": 38, "days_left": 8.1, "reorder_level": 250, "risk": "low", "batch_number": "BATCH-004"},
    {"id": "stock-5", "name": "Insulin vials", "facility_id": "phc-gajuwaka", "current_stock": 42, "avg_daily_usage": 9, "days_left": 4.7, "reorder_level": 70, "risk": "medium", "batch_number": "BATCH-005"},
    {"id": "stock-6", "name": "Zinc tablets", "facility_id": "chc-narsipatnam", "current_stock": 220, "avg_daily_usage": 14, "days_left": 15.7, "reorder_level": 110, "risk": "low", "batch_number": "BATCH-006"},
    {"id": "stock-7", "name": "Paracetamol 650mg", "facility_id": "phc-pendurthi", "current_stock": 350, "avg_daily_usage": 25, "days_left": 14.0, "reorder_level": 150, "risk": "low", "batch_number": "BATCH-007"},
    {"id": "stock-8", "name": "ORS packets", "facility_id": "phc-pendurthi", "current_stock": 280, "avg_daily_usage": 20, "days_left": 14.0, "reorder_level": 120, "risk": "low", "batch_number": "BATCH-008"},
    {"id": "stock-9", "name": "Metformin", "facility_id": "phc-pendurthi", "current_stock": 150, "avg_daily_usage": 18, "days_left": 8.3, "reorder_level": 100, "risk": "low", "batch_number": "BATCH-009"},
    {"id": "stock-10", "name": "Paracetamol 650mg", "facility_id": "phc-ananthapuram", "current_stock": 200, "avg_daily_usage": 15, "days_left": 13.3, "reorder_level": 100, "risk": "low", "batch_number": "BATCH-010"},
    {"id": "stock-11", "name": "Amoxicillin", "facility_id": "phc-ananthapuram", "current_stock": 80, "avg_daily_usage": 12, "days_left": 6.7, "reorder_level": 70, "risk": "medium", "batch_number": "BATCH-011"},
    {"id": "stock-12", "name": "ORS packets", "facility_id": "phc-ananthapuram", "current_stock": 120, "avg_daily_usage": 10, "days_left": 12.0, "reorder_level": 60, "risk": "low", "batch_number": "BATCH-012"},
    {"id": "stock-13", "name": "Amlodipine", "facility_id": "phc-ananthapuram", "current_stock": 90, "avg_daily_usage": 8, "days_left": 11.3, "reorder_level": 50, "risk": "low", "batch_number": "BATCH-013"},
    {"id": "stock-14", "name": "Paracetamol 650mg", "facility_id": "phc-rushikonda", "current_stock": 45, "avg_daily_usage": 28, "days_left": 1.6, "reorder_level": 160, "risk": "critical", "batch_number": "BATCH-014"},
    {"id": "stock-15", "name": "Dengue NS1 kits", "facility_id": "phc-rushikonda", "current_stock": 35, "avg_daily_usage": 12, "days_left": 2.9, "reorder_level": 80, "risk": "high", "batch_number": "BATCH-015"},
    {"id": "stock-16", "name": "Metformin", "facility_id": "phc-rushikonda", "current_stock": 180, "avg_daily_usage": 15, "days_left": 12.0, "reorder_level": 100, "risk": "low", "batch_number": "BATCH-016"},
    {"id": "stock-17", "name": "Amlodipine", "facility_id": "chc-waltair", "current_stock": 55, "avg_daily_usage": 22, "days_left": 2.5, "reorder_level": 150, "risk": "critical", "batch_number": "BATCH-017"},
    {"id": "stock-18", "name": "Clopidogrel", "facility_id": "chc-waltair", "current_stock": 90, "avg_daily_usage": 18, "days_left": 5.0, "reorder_level": 120, "risk": "high", "batch_number": "BATCH-018"},
    {"id": "stock-19", "name": "Atorvastatin", "facility_id": "chc-waltair", "current_stock": 200, "avg_daily_usage": 20, "days_left": 10.0, "reorder_level": 130, "risk": "low", "batch_number": "BATCH-019"},
    {"id": "stock-20", "name": "Paracetamol 650mg", "facility_id": "phc-yendada", "current_stock": 260, "avg_daily_usage": 18, "days_left": 14.4, "reorder_level": 100, "risk": "low", "batch_number": "BATCH-020"},
    {"id": "stock-21", "name": "ORS packets", "facility_id": "phc-malkapuram", "current_stock": 170, "avg_daily_usage": 15, "days_left": 11.3, "reorder_level": 90, "risk": "low", "batch_number": "BATCH-021"},
    {"id": "stock-22", "name": "Amoxicillin", "facility_id": "phc-malkapuram", "current_stock": 60, "avg_daily_usage": 14, "days_left": 4.3, "reorder_level": 100, "risk": "high", "batch_number": "BATCH-022"},
    {"id": "stock-23", "name": "Iron tablets", "facility_id": "phc-gavaravaram", "current_stock": 160, "avg_daily_usage": 8, "days_left": 20.0, "reorder_level": 80, "risk": "low", "batch_number": "BATCH-023"},
    {"id": "stock-24", "name": "Paracetamol 650mg", "facility_id": "chc-devarapalle", "current_stock": 110, "avg_daily_usage": 25, "days_left": 4.4, "reorder_level": 150, "risk": "high", "batch_number": "BATCH-024"},
    {"id": "stock-25", "name": "ORS packets", "facility_id": "chc-devarapalle", "current_stock": 85, "avg_daily_usage": 20, "days_left": 4.3, "reorder_level": 120, "risk": "high", "batch_number": "BATCH-025"},
    {"id": "stock-26", "name": "Insulin vials", "facility_id": "chc-waltair", "current_stock": 30, "avg_daily_usage": 8, "days_left": 3.8, "reorder_level": 60, "risk": "critical", "batch_number": "BATCH-026"},
    {"id": "stock-27", "name": "Metformin", "facility_id": "phc-gajuwaka", "current_stock": 200, "avg_daily_usage": 16, "days_left": 12.5, "reorder_level": 100, "risk": "low", "batch_number": "BATCH-027"},
    {"id": "stock-28", "name": "Salbutamol inhaler", "facility_id": "phc-malkapuram", "current_stock": 25, "avg_daily_usage": 6, "days_left": 4.2, "reorder_level": 40, "risk": "high", "batch_number": "BATCH-028"},
    {"id": "stock-29", "name": "Metronidazole", "facility_id": "chc-devarapalle", "current_stock": 130, "avg_daily_usage": 12, "days_left": 10.8, "reorder_level": 80, "risk": "low", "batch_number": "BATCH-029"},
    {"id": "stock-30", "name": "Paracetamol 650mg", "facility_id": "phc-gavaravaram", "current_stock": 180, "avg_daily_usage": 10, "days_left": 18.0, "reorder_level": 80, "risk": "low", "batch_number": "BATCH-030"},
]

SEED_INSIGHTS = [
    {"id": "I001", "message": "PHC Madhurawada is critical due to 96% bed occupancy and reduced doctor availability.", "priority": "high", "category": "Facility Risk", "timestamp": "4 min ago", "type": "Facility Risk Insight", "facility_id": "phc-madhurawada", "severity": "critical", "created_at": "2026-07-05T09:10:00+05:30", "summary": "Bed occupancy is at 96% with doctor capacity under pressure.", "recommendation": "Send doctor support, route stable patients to nurse-led screening, and prepare diversion protocol.", "status": "open"},
    {"id": "I002", "message": "23 medicine stock alerts detected across 9 facilities, led by Paracetamol and ORS.", "priority": "high", "category": "Inventory", "timestamp": "12 min ago", "type": "Medicine Stock-out Alert", "facility_id": "phc-madhurawada", "severity": "high", "created_at": "2026-07-05T09:02:00+05:30", "summary": "Paracetamol and ORS will breach stock-out threshold within 72 hours.", "recommendation": "Approve transfer from PHC Pendurthi and CHC Narsipatnam stock buffers.", "status": "open"},
    {"id": "I003", "message": "Dengue cases increased 136% week over week in Bheemunipatnam and nearby clusters.", "priority": "high", "category": "Disease Surveillance", "timestamp": "28 min ago", "type": "Disease Spike Alert", "facility_id": "chc-bheemunipatnam", "severity": "high", "created_at": "2026-07-05T08:46:00+05:30", "summary": "Dengue cases are rising across Bheemunipatnam, Gajuwaka, and Madhurawada.", "recommendation": "Activate fever desk, local surveillance, and ORS buffer distribution.", "status": "acknowledged"},
    {"id": "I004", "message": "Nurse follow-up backlog is rising for high-risk respiratory patients in Gajuwaka.", "priority": "medium", "category": "Workload", "timestamp": "41 min ago", "type": "Nurse Overload Alert", "facility_id": "phc-gajuwaka", "severity": "medium", "created_at": "2026-07-05T08:33:00+05:30", "summary": "Follow-up backlog is rising for high-risk respiratory patients.", "recommendation": "Optimize field route and reassign stable follow-ups to available nurses.", "status": "open"},
    {"id": "I005", "message": "CHC Narsipatnam can donate buffer stock without breaching reserve levels.", "priority": "low", "category": "Supply Chain", "timestamp": "1 hr ago", "type": "Stock Transfer Opportunity", "facility_id": "chc-narsipatnam", "severity": "low", "created_at": "2026-07-05T08:00:00+05:30", "summary": "Narsipatnam has adequate Zinc and Paracetamol buffer stock.", "recommendation": "Use as first transfer source for PHC Madhurawada demand surge.", "status": "resolved"},
    {"id": "I006", "message": "PHC Ananthapuram has low patient volume. Consider rotating staff.", "priority": "low", "category": "Workload", "timestamp": "2 hr ago", "type": "Low Utilization Alert", "facility_id": "phc-ananthapuram", "severity": "low", "created_at": "2026-07-05T07:00:00+05:30", "summary": "Patient volume is below threshold at Ananthapuram.", "recommendation": "Review staffing allocation and consider cross-facility support.", "status": "open"},
    {"id": "I007", "message": "PHC Pendurthi stock levels adequate. Monitor weekly.", "priority": "low", "category": "Inventory", "timestamp": "3 hr ago", "type": "Stock Level Notice", "facility_id": "phc-pendurthi", "severity": "low", "created_at": "2026-07-05T06:00:00+05:30", "summary": "All medicine stocks are above reorder levels.", "recommendation": "Continue routine monitoring.", "status": "open"},
    {"id": "I008", "message": "CHC Waltair reporting 3 cardiac emergencies in last 24 hours. ICU at capacity.", "priority": "high", "category": "Facility Risk", "timestamp": "15 min ago", "type": "Emergency Surge Alert", "facility_id": "chc-waltair", "severity": "critical", "created_at": "2026-07-05T08:55:00+05:30", "summary": "ICU beds fully occupied, 2 patients on ventilator support.", "recommendation": "Activate emergency protocol, divert stable cases to PHC Rushikonda.", "status": "open"},
    {"id": "I009", "message": "Dengue cluster detected in Rushikonda beach area. 12 cases this week.", "priority": "high", "category": "Disease Surveillance", "timestamp": "35 min ago", "type": "Outbreak Alert", "facility_id": "phc-rushikonda", "severity": "high", "created_at": "2026-07-05T08:35:00+05:30", "summary": "Rapid antigen tests confirm dengue cluster in coastal neighborhoods.", "recommendation": "Deploy fogging teams, distribute mosquito nets, activate fever camps.", "status": "open"},
    {"id": "I010", "message": "Insulin vials critically low at CHC Waltair. Only 30 units remaining.", "priority": "high", "category": "Inventory", "timestamp": "20 min ago", "type": "Stock-out Warning", "facility_id": "chc-waltair", "severity": "critical", "created_at": "2026-07-05T08:50:00+05:30", "summary": "Insulin stock will run out in 3.8 days at current consumption.", "recommendation": "Emergency procurement or inter-facility transfer from PHC Pendurthi.", "status": "open"},
    {"id": "I011", "message": "PHC Rushikonda Paracetamol stock at 45 units. Critical shortage imminent.", "priority": "high", "category": "Inventory", "timestamp": "8 min ago", "type": "Stock-out Warning", "facility_id": "phc-rushikonda", "severity": "critical", "created_at": "2026-07-05T09:02:00+05:30", "summary": "Only 1.6 days of Paracetamol remaining amid dengue surge.", "recommendation": "Immediate transfer from PHC Pendurthi surplus stock.", "status": "open"},
    {"id": "I012", "message": "CHC Devarapalle doctor absenteeism impacting maternal care throughput.", "priority": "medium", "category": "Workload", "timestamp": "45 min ago", "type": "Staffing Alert", "facility_id": "chc-devarapalle", "severity": "medium", "created_at": "2026-07-05T08:25:00+05:30", "summary": "Dr. Mohan Krishna absent. Dr. Sita Devi handling 2x patient load.", "recommendation": "Deploy medical officer from Ananthapuram for afternoon shift coverage.", "status": "open"},
    {"id": "I013", "message": "PHC Gajuwaka reporting spike in pediatric respiratory cases.", "priority": "medium", "category": "Disease Surveillance", "timestamp": "55 min ago", "type": "Seasonal Alert", "facility_id": "phc-gajuwaka", "severity": "medium", "created_at": "2026-07-05T08:15:00+05:30", "summary": "18 pediatric ARI cases in last 48 hours, mostly from Malkapuram area.", "recommendation": "Ensure Salbutamol nebulizer supplies. Consider mobile health van deployment.", "status": "acknowledged"},
    {"id": "I014", "message": "CHC Bheemunipatnam blood bank O-negative reserves critically low.", "priority": "high", "category": "Inventory", "timestamp": "1 hr ago", "type": "Critical Supply Alert", "facility_id": "chc-bheemunipatnam", "severity": "high", "created_at": "2026-07-05T08:00:00+05:30", "summary": "Only 2 units O-negative remaining. Emergency transfusion cases may be affected.", "recommendation": "Coordinate blood donation camp. Request emergency supply from district blood bank.", "status": "open"},
    {"id": "I015", "message": "PHC Yendada stable. All metrics within normal parameters.", "priority": "low", "category": "Operations", "timestamp": "4 hr ago", "type": "Status Update", "facility_id": "phc-yendada", "severity": "low", "created_at": "2026-07-05T05:30:00+05:30", "summary": "OPD flow normal, staff attendance 100%, no pending critical follow-ups.", "recommendation": "Continue standard operating procedures.", "status": "resolved"},
]

SEED_DISEASE_SPIKES = [
    {"condition": "Fever", "facility_id": "phc-madhurawada", "this_week": 84, "last_week": 41, "increase": 104, "risk": "critical", "linked_medicine": "Paracetamol, ORS"},
    {"condition": "Dengue", "facility_id": "chc-bheemunipatnam", "this_week": 26, "last_week": 11, "increase": 136, "risk": "high", "linked_medicine": "ORS, platelet kits"},
    {"condition": "ARI", "facility_id": "phc-gajuwaka", "this_week": 52, "last_week": 37, "increase": 41, "risk": "medium", "linked_medicine": "Salbutamol, Amoxicillin"},
    {"condition": "Diarrhea", "facility_id": "phc-pendurthi", "this_week": 19, "last_week": 22, "increase": -14, "risk": "low", "linked_medicine": "ORS, Zinc"},
    {"condition": "Dengue", "facility_id": "phc-rushikonda", "this_week": 38, "last_week": 14, "increase": 171, "risk": "critical", "linked_medicine": "Paracetamol, ORS, platelet kits"},
    {"condition": "Cardiac", "facility_id": "chc-waltair", "this_week": 15, "last_week": 8, "increase": 88, "risk": "high", "linked_medicine": "Atorvastatin, Clopidogrel, Amlodipine"},
    {"condition": "Malaria", "facility_id": "phc-rushikonda", "this_week": 11, "last_week": 5, "increase": 120, "risk": "high", "linked_medicine": "Chloroquine, Primaquine"},
    {"condition": "Pediatric ARI", "facility_id": "phc-gajuwaka", "this_week": 18, "last_week": 9, "increase": 100, "risk": "high", "linked_medicine": "Amoxicillin, Salbutamol"},
    {"condition": "Fever", "facility_id": "chc-waltair", "this_week": 62, "last_week": 45, "increase": 38, "risk": "medium", "linked_medicine": "Paracetamol, ORS"},
    {"condition": "Diabetes complications", "facility_id": "chc-narsipatnam", "this_week": 14, "last_week": 10, "increase": 40, "risk": "medium", "linked_medicine": "Metformin, Insulin"},
    {"condition": "Maternal complications", "facility_id": "chc-devarapalle", "this_week": 8, "last_week": 5, "increase": 60, "risk": "medium", "linked_medicine": "Iron tablets, Folic acid"},
    {"condition": "Skin infections", "facility_id": "phc-malkapuram", "this_week": 22, "last_week": 18, "increase": 22, "risk": "low", "linked_medicine": "Metronidazole, Antibiotics"},
]

SEED_HEALTH_TRENDS = [
    {"month": "Jan", "op_visits": 2840, "chronic_cases": 420, "follow_ups": 1120, "fever": 38, "respiratory": 21, "hypertension": 48, "diabetes": 42, "diarrhea": 16},
    {"month": "Feb", "op_visits": 3020, "chronic_cases": 445, "follow_ups": 1180, "fever": 42, "respiratory": 24, "hypertension": 51, "diabetes": 44, "diarrhea": 18},
    {"month": "Mar", "op_visits": 3180, "chronic_cases": 470, "follow_ups": 1240, "fever": 49, "respiratory": 27, "hypertension": 54, "diabetes": 47, "diarrhea": 20},
    {"month": "Apr", "op_visits": 2950, "chronic_cases": 458, "follow_ups": 1190, "fever": 46, "respiratory": 25, "hypertension": 53, "diabetes": 46, "diarrhea": 17},
    {"month": "May", "op_visits": 3410, "chronic_cases": 492, "follow_ups": 1310, "fever": 58, "respiratory": 31, "hypertension": 57, "diabetes": 49, "diarrhea": 19},
    {"month": "Jun", "op_visits": 3650, "chronic_cases": 518, "follow_ups": 1420, "fever": 66, "respiratory": 39, "hypertension": 61, "diabetes": 52, "diarrhea": 22},
    {"month": "Jul", "op_visits": 3890, "chronic_cases": 542, "follow_ups": 1510, "fever": 84, "respiratory": 52, "hypertension": 65, "diabetes": 56, "diarrhea": 19},
]

SEED_VILLAGE_CONDITIONS = [
    {"village": "Madhurawada", "facility_id": "phc-madhurawada", "condition": "Fever", "count": 48},
    {"village": "Rushikonda", "facility_id": "phc-rushikonda", "condition": "Dengue cluster", "count": 38},
    {"village": "Bheemunipatnam", "facility_id": "chc-bheemunipatnam", "condition": "Dengue watch", "count": 26},
    {"village": "Gajuwaka", "facility_id": "phc-gajuwaka", "condition": "Pediatric ARI", "count": 31},
    {"village": "Pendurthi", "facility_id": "phc-pendurthi", "condition": "Diarrhea", "count": 12},
    {"village": "Waltair Uplands", "facility_id": "chc-waltair", "condition": "Cardiac surge", "count": 15},
    {"village": "Lawsons Bay", "facility_id": "chc-waltair", "condition": "Hypertension follow-ups", "count": 22},
    {"village": "Yendada", "facility_id": "phc-yendada", "condition": "Chronic disease management", "count": 18},
    {"village": "Seethammadhara", "facility_id": "phc-yendada", "condition": "Geriatric care", "count": 14},
    {"village": "Malkapuram", "facility_id": "phc-malkapuram", "condition": "Skin infections", "count": 22},
    {"village": "Steel Plant", "facility_id": "phc-malkapuram", "condition": "Occupational injuries", "count": 9},
    {"village": "Gavaravaram", "facility_id": "phc-gavaravaram", "condition": "Maternal care", "count": 8},
    {"village": "Chintapalle", "facility_id": "phc-gavaravaram", "condition": "Pediatric fever", "count": 11},
    {"village": "Devarapalle", "facility_id": "chc-devarapalle", "condition": "Maternal high-risk", "count": 8},
    {"village": "Paderu", "facility_id": "chc-devarapalle", "condition": "Respiratory illness", "count": 16},
    {"village": "Tagarapuvalasa", "facility_id": "chc-bheemunipatnam", "condition": "UTI cases", "count": 7},
    {"village": "Narsipatnam", "facility_id": "chc-narsipatnam", "condition": "Diabetes management", "count": 14},
    {"village": "Beach Road", "facility_id": "phc-rushikonda", "condition": "Dermatitis", "count": 10},
]


async def _seed_table(session: AsyncSession, model, data: list[dict]):
    result = await session.execute(select(model))
    if result.scalars().first() is None:
        for row in data:
            session.add(model(**row))
        await session.commit()


async def seed_database():
    async with async_session() as session:
        await _seed_table(session, Facility, SEED_FACILITIES)
        await _seed_table(session, Doctor, SEED_DOCTORS)
        await _seed_table(session, Nurse, SEED_NURSES)
        await _seed_table(session, Patient, SEED_PATIENTS)
        await _seed_table(session, InventoryStock, SEED_INVENTORY)
        await _seed_table(session, AIInsight, SEED_INSIGHTS)
        await _seed_table(session, DiseaseSpike, SEED_DISEASE_SPIKES)
        await _seed_table(session, HealthTrend, SEED_HEALTH_TRENDS)
        await _seed_table(session, VillageCondition, SEED_VILLAGE_CONDITIONS)


async def reseed_database():
    """Drop all data and re-seed from scratch."""
    async with async_session() as session:
        for table in ['village_conditions', 'health_trends', 'disease_spikes', 'ai_insights', 'inventory_stock', 'inventory_log', 'patients', 'nurses', 'doctors', 'facilities']:
            await session.execute(text(f'TRUNCATE TABLE {table} RESTART IDENTITY CASCADE'))
        await session.commit()

    async with async_session() as session:
        for row in SEED_FACILITIES:
            session.add(Facility(**row))
        for row in SEED_DOCTORS:
            session.add(Doctor(**row))
        for row in SEED_NURSES:
            session.add(Nurse(**row))
        for row in SEED_PATIENTS:
            session.add(Patient(**row))
        for row in SEED_INVENTORY:
            session.add(InventoryStock(**row))
        for row in SEED_INSIGHTS:
            session.add(AIInsight(**row))
        for row in SEED_DISEASE_SPIKES:
            session.add(DiseaseSpike(**row))
        for row in SEED_HEALTH_TRENDS:
            session.add(HealthTrend(**row))
        for row in SEED_VILLAGE_CONDITIONS:
            session.add(VillageCondition(**row))
        await session.commit()
