"use client"

import { useState } from "react"
import { motion } from "framer-motion"
import { useDashboard } from "@/hooks/use-dashboard"
import { useStore } from "@/store/use-store"
import { useRouter } from "next/navigation"
import { MetricCard } from "@/components/dashboard/metric-card"
import { ChartCard } from "@/components/dashboard/chart-card"
import { RiskRankingTable } from "@/components/dashboard/risk-ranking-table"
import { RecentAlerts } from "@/components/dashboard/recent-alerts"
import { TopCriticalFacilities } from "@/components/dashboard/top-critical-facilities"
import { CreateFacilityDialog } from "@/components/facilities/create-facility-dialog"
import { LoadingSkeleton } from "@/components/shared/loading-skeleton"
import { Button } from "@/components/ui/button"
import {
  Building2, Activity, Pill, Stethoscope, HandHeart, AlertTriangle,
  BedDouble, Users, TrendingUp, Plus, FileText, BarChart3, Download,
} from "lucide-react"
import {
  AreaChart, Area, BarChart, Bar,
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend
} from "recharts"
import { formatNumber } from "@/lib/utils"

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.06 }
  }
}

export default function DashboardPage() {
  const router = useRouter()
  const { data, loading } = useDashboard()
  const role = useStore((s) => s.role)
  const [selectedChart, setSelectedChart] = useState<"area" | "bar">("area")
  const [showCreateFacility, setShowCreateFacility] = useState(false)

  if (role !== "district_officer") {
    router.push("/dashboard")
    return null
  }

  if (loading) return <LoadingSkeleton type="dashboard" />
  if (!data) return null

  const metrics = [
    { title: "Total Facilities", value: data.totalFacilities, icon: <Building2 className="h-6 w-6" />, variant: "default" as const, trend: 2.5, subtitle: "vs last month" },
    { title: "Critical Facilities", value: data.criticalFacilities, icon: <AlertTriangle className="h-6 w-6" />, variant: "danger" as const, trend: 8.1, subtitle: "vs yesterday" },
    { title: "Medicine Alerts", value: data.medicineAlerts, icon: <Pill className="h-6 w-6" />, variant: "warning" as const, trend: -3.2, subtitle: "vs last week" },
    { title: "Doctor Absence", value: data.doctorAbsence, icon: <Stethoscope className="h-6 w-6" />, variant: "danger" as const, trend: 12.5, subtitle: "unusual increase" },
    { title: "Nurse Overload", value: data.nurseOverload, icon: <HandHeart className="h-6 w-6" />, variant: "warning" as const, trend: 5.0, subtitle: "vs last week" },
    { title: "Disease Alerts", value: data.diseaseAlerts, icon: <Activity className="h-6 w-6" />, variant: "danger" as const, trend: 15.3, subtitle: "seasonal spike" },
    { title: "Bed Pressure", value: data.bedPressure, icon: <BedDouble className="h-6 w-6" />, variant: "warning" as const, trend: -1.8, subtitle: "slight improvement" },
    { title: "High Risk Patients", value: data.highRiskPatients, icon: <Users className="h-6 w-6" />, variant: "danger" as const, trend: 7.2, subtitle: "needs attention" },
  ]

  const roleFilteredMetrics = metrics

  const generateBrief = () => {
    const title = "District Health Brief"
    const date = new Date().toLocaleDateString("en-IN", { weekday: "long", year: "numeric", month: "long", day: "numeric" })
    const content = `
      <div style="font-family:system-ui,sans-serif;padding:40px;color:#1a1a2e">
        <div style="text-align:center;margin-bottom:32px">
          <h1 style="font-size:24px;margin:0;color:#1a1a2e">${title}</h1>
          <p style="color:#666;margin:4px 0 0 0">${date}</p>
        </div>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:24px">
          ${data ? metrics.map(m => `
            <div style="background:#f8f9fa;border-radius:8px;padding:12px 16px">
              <p style="margin:0;font-size:12px;color:#666">${m.title}</p>
              <p style="margin:4px 0 0;font-size:20px;font-weight:700">${m.value}</p>
              <p style="margin:2px 0 0;font-size:11px;color:#999">${m.trend > 0 ? "+" : ""}${m.trend}% ${m.subtitle}</p>
            </div>
          `).join("") : ""}
        </div>
        <div style="border-top:2px solid #eee;padding-top:16px">
          <p style="font-size:11px;color:#999;text-align:center">
            Generated by Arogyam Smart Health Platform
          </p>
        </div>
      </div>
    `
    const win = window.open("", "_blank")
    if (win) {
      win.document.write(`<!DOCTYPE html><html><head><title>${title}</title></head><body>${content}</body></html>`)
      win.document.close()
      win.print()
    }
  }

  const roleGreeting: Record<string, string> = {
    district_officer: "District Officer",
    doctor: "Doctor",
    nurse: "Nurse",
  }

  const CustomTooltip = ({ active, payload, label }: any) => {
    if (active && payload && payload.length) {
      return (
        <div className="rounded-xl border border-border/50 bg-background/95 p-3.5 shadow-xl backdrop-blur-xl text-sm">
          <p className="mb-1.5 font-semibold">{label}</p>
          <div className="space-y-1">
            {payload.map((entry: any, idx: number) => (
              <div key={idx} className="flex items-center gap-2">
                <span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: entry.color }} />
                <span className="text-muted-foreground">{entry.name}:</span>
                <span className="font-medium tabular-nums">{formatNumber(entry.value)}</span>
              </div>
            ))}
          </div>
        </div>
      )
    }
    return null
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-start gap-3">
          <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-[#7C3AED]/20 via-[#4648d4]/10 to-[#3B82F6]/10 shadow-sm ring-1 ring-[#7C3AED]/20">
            <img src="/logo.png" alt="Arogyam" className="h-7 w-7 object-contain" />
          </div>
          <div>
            <h1 className="text-2xl font-bold tracking-tight sm:text-3xl bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text">
              Dashboard
            </h1>
            <p className="mt-1 text-sm text-muted-foreground">
              Welcome back, {roleGreeting[role] || "User"}. Here&apos;s your command center.
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" className="h-9 gap-1.5 rounded-xl text-xs">
            <Download className="h-3.5 w-3.5" />
            Export
          </Button>
          <Button variant="outline" size="sm" className="h-9 gap-1.5 rounded-xl text-xs" onClick={generateBrief}>
            <FileText className="h-3.5 w-3.5" />
            Generate Brief
          </Button>
          {role === "district_officer" && (
            <Button
              size="sm"
              className="h-9 gap-1.5 rounded-xl text-xs bg-gradient-to-r from-[#7C3AED] via-[#4648d4] to-[#3B82F6] hover:from-[#6D28D9] hover:via-[#4338CA] hover:to-[#2563EB] shadow-lg shadow-[#7C3AED]/20"
              onClick={() => setShowCreateFacility(true)}
            >
              <Plus className="h-3.5 w-3.5" />
              Create Facility
            </Button>
          )}
        </div>
      </div>

      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4"
      >
        {roleFilteredMetrics.map((metric) => (
          <MetricCard key={metric.title} {...metric} />
        ))}
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <ChartCard
          title="Facility Risk Trend"
          subtitle="Risk distribution across facilities over time"
          action={
            <div className="flex items-center gap-1 rounded-lg bg-muted p-0.5">
              <Button
                variant={selectedChart === "area" ? "default" : "ghost"}
                size="sm"
                className="h-7 px-2.5"
                onClick={() => setSelectedChart("area")}
              >
                <TrendingUp className="h-3.5 w-3.5" />
              </Button>
              <Button
                variant={selectedChart === "bar" ? "default" : "ghost"}
                size="sm"
                className="h-7 px-2.5"
                onClick={() => setSelectedChart("bar")}
              >
                <BarChart3 className="h-3.5 w-3.5" />
              </Button>
            </div>
          }
        >
          <ResponsiveContainer width="100%" height="100%">
            {selectedChart === "area" ? (
              <AreaChart data={data.facilityRiskTrend}>
                <defs>
                  <linearGradient id="colorLow" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#22c55e" stopOpacity={0.35}/><stop offset="95%" stopColor="#22c55e" stopOpacity={0}/></linearGradient>
                  <linearGradient id="colorMedium" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#eab308" stopOpacity={0.35}/><stop offset="95%" stopColor="#eab308" stopOpacity={0}/></linearGradient>
                  <linearGradient id="colorHigh" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#f97316" stopOpacity={0.35}/><stop offset="95%" stopColor="#f97316" stopOpacity={0}/></linearGradient>
                  <linearGradient id="colorCritical" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#ef4444" stopOpacity={0.35}/><stop offset="95%" stopColor="#ef4444" stopOpacity={0}/></linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" opacity={0.3} />
                <XAxis dataKey="date" tick={{ fontSize: 12 }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fontSize: 12 }} axisLine={false} tickLine={false} />
                <Tooltip content={<CustomTooltip />} />
                <Area type="monotone" dataKey="low" stackId="1" stroke="#22c55e" fill="url(#colorLow)" strokeWidth={2} />
                <Area type="monotone" dataKey="medium" stackId="1" stroke="#eab308" fill="url(#colorMedium)" strokeWidth={2} />
                <Area type="monotone" dataKey="high" stackId="1" stroke="#f97316" fill="url(#colorHigh)" strokeWidth={2} />
                <Area type="monotone" dataKey="critical" stackId="1" stroke="#ef4444" fill="url(#colorCritical)" strokeWidth={2} />
                <Legend wrapperStyle={{ fontSize: 12 }} />
              </AreaChart>
            ) : (
              <BarChart data={data.facilityRiskTrend}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" opacity={0.3} />
                <XAxis dataKey="date" tick={{ fontSize: 12 }} axisLine={false} tickLine={false} />
                <YAxis tick={{ fontSize: 12 }} axisLine={false} tickLine={false} />
                <Tooltip content={<CustomTooltip />} />
                <Bar dataKey="low" stackId="a" fill="#22c55e" radius={[0, 0, 0, 0]} />
                <Bar dataKey="medium" stackId="a" fill="#eab308" />
                <Bar dataKey="high" stackId="a" fill="#f97316" />
                <Bar dataKey="critical" stackId="a" fill="#ef4444" radius={[4, 4, 0, 0]} />
                <Legend wrapperStyle={{ fontSize: 12 }} />
              </BarChart>
            )}
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Medicine Stock Trend" subtitle="Current stock vs required over time">
          <ResponsiveContainer width="100%" height="100%">
            <AreaChart data={data.medicineStockTrend}>
              <defs>
                <linearGradient id="colorStock" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#3b82f6" stopOpacity={0.35}/><stop offset="95%" stopColor="#3b82f6" stopOpacity={0}/></linearGradient>
                <linearGradient id="colorRequired" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#ef4444" stopOpacity={0.35}/><stop offset="95%" stopColor="#ef4444" stopOpacity={0}/></linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" opacity={0.3} />
              <XAxis dataKey="date" tick={{ fontSize: 12 }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fontSize: 12 }} axisLine={false} tickLine={false} />
              <Tooltip content={<CustomTooltip />} />
              <Area type="monotone" dataKey="stock" stroke="#3b82f6" fill="url(#colorStock)" strokeWidth={2} />
              <Area type="monotone" dataKey="required" stroke="#ef4444" fill="url(#colorRequired)" strokeWidth={2} />
              <Legend wrapperStyle={{ fontSize: 12 }} />
            </AreaChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <ChartCard title="Patient Visits" subtitle="OPD & IPD trends">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={data.patientVisits}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" opacity={0.3} />
              <XAxis dataKey="date" tick={{ fontSize: 12 }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fontSize: 12 }} axisLine={false} tickLine={false} />
              <Tooltip content={<CustomTooltip />} />
              <Bar dataKey="opd" name="OPD" fill="#3b82f6" radius={[4, 4, 0, 0]} />
              <Bar dataKey="ipd" name="IPD" fill="#06b6d4" radius={[4, 4, 0, 0]} />
              <Legend wrapperStyle={{ fontSize: 12 }} />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Disease Cases" subtitle="Current disease distribution">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={data.diseaseCases} layout="vertical">
              <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" opacity={0.3} />
              <XAxis type="number" tick={{ fontSize: 12 }} axisLine={false} tickLine={false} />
              <YAxis dataKey="disease" type="category" tick={{ fontSize: 11 }} width={90} axisLine={false} tickLine={false} />
              <Tooltip content={<CustomTooltip />} />
              <Bar dataKey="cases" fill="#8b5cf6" radius={[0, 4, 4, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
        <RiskRankingTable data={data.facilityRiskRanking} />
        <RecentAlerts alerts={data.recentAlerts} />
      </div>

      <TopCriticalFacilities facilities={data.topCriticalFacilities} />

      <CreateFacilityDialog
        open={showCreateFacility}
        onOpenChange={setShowCreateFacility}
      />
    </div>
  )
}
